/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ningso_curlhttp_CurlHttpUtils */

#ifndef _Included_com_ningso_curlhttp_CurlHttpUtils
#define _Included_com_ningso_curlhttp_CurlHttpUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ningso_curljnihttp_CurlHttpUtils
 * Method:    getUrl
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ningso_curljnihttp_CurlHttpUtils_getUrl
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

/*
 * Class:     com_ningso_curljnihttp_CurlHttpUtils
 * Method:    postUrl
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ningso_curljnihttp_CurlHttpUtils_postUrl
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
